# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pepper/Project/MMORPG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pepper/Project/MMORPG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pepper/Project/MMORPG/CMakeFiles /home/pepper/Project/MMORPG/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pepper/Project/MMORPG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

#=============================================================================
# Target rules for targets named SOIL

# Build rule for target.
SOIL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SOIL
.PHONY : SOIL

# fast build rule for target.
SOIL/fast:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/build
.PHONY : SOIL/fast

#=============================================================================
# Target rules for targets named GLEW

# Build rule for target.
GLEW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GLEW
.PHONY : GLEW

# fast build rule for target.
GLEW/fast:
	$(MAKE) -f CMakeFiles/GLEW.dir/build.make CMakeFiles/GLEW.dir/build
.PHONY : GLEW/fast

#=============================================================================
# Target rules for targets named nite

# Build rule for target.
nite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nite
.PHONY : nite

# fast build rule for target.
nite/fast:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/build
.PHONY : nite/fast

#=============================================================================
# Target rules for targets named src

# Build rule for target.
src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src
.PHONY : src

# fast build rule for target.
src/fast:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/build
.PHONY : src/fast

src/AI/AI.o: src/AI/AI.cpp.o

.PHONY : src/AI/AI.o

# target to build an object file
src/AI/AI.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/AI/AI.cpp.o
.PHONY : src/AI/AI.cpp.o

src/AI/AI.i: src/AI/AI.cpp.i

.PHONY : src/AI/AI.i

# target to preprocess a source file
src/AI/AI.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/AI/AI.cpp.i
.PHONY : src/AI/AI.cpp.i

src/AI/AI.s: src/AI/AI.cpp.s

.PHONY : src/AI/AI.s

# target to generate assembly for a file
src/AI/AI.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/AI/AI.cpp.s
.PHONY : src/AI/AI.cpp.s

src/Engine/Animation.o: src/Engine/Animation.cpp.o

.PHONY : src/Engine/Animation.o

# target to build an object file
src/Engine/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Animation.cpp.o
.PHONY : src/Engine/Animation.cpp.o

src/Engine/Animation.i: src/Engine/Animation.cpp.i

.PHONY : src/Engine/Animation.i

# target to preprocess a source file
src/Engine/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Animation.cpp.i
.PHONY : src/Engine/Animation.cpp.i

src/Engine/Animation.s: src/Engine/Animation.cpp.s

.PHONY : src/Engine/Animation.s

# target to generate assembly for a file
src/Engine/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Animation.cpp.s
.PHONY : src/Engine/Animation.cpp.s

src/Engine/Audio.o: src/Engine/Audio.cpp.o

.PHONY : src/Engine/Audio.o

# target to build an object file
src/Engine/Audio.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Audio.cpp.o
.PHONY : src/Engine/Audio.cpp.o

src/Engine/Audio.i: src/Engine/Audio.cpp.i

.PHONY : src/Engine/Audio.i

# target to preprocess a source file
src/Engine/Audio.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Audio.cpp.i
.PHONY : src/Engine/Audio.cpp.i

src/Engine/Audio.s: src/Engine/Audio.cpp.s

.PHONY : src/Engine/Audio.s

# target to generate assembly for a file
src/Engine/Audio.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Audio.cpp.s
.PHONY : src/Engine/Audio.cpp.s

src/Engine/Console.o: src/Engine/Console.cpp.o

.PHONY : src/Engine/Console.o

# target to build an object file
src/Engine/Console.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Console.cpp.o
.PHONY : src/Engine/Console.cpp.o

src/Engine/Console.i: src/Engine/Console.cpp.i

.PHONY : src/Engine/Console.i

# target to preprocess a source file
src/Engine/Console.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Console.cpp.i
.PHONY : src/Engine/Console.cpp.i

src/Engine/Console.s: src/Engine/Console.cpp.s

.PHONY : src/Engine/Console.s

# target to generate assembly for a file
src/Engine/Console.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Console.cpp.s
.PHONY : src/Engine/Console.cpp.s

src/Engine/Font.o: src/Engine/Font.cpp.o

.PHONY : src/Engine/Font.o

# target to build an object file
src/Engine/Font.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Font.cpp.o
.PHONY : src/Engine/Font.cpp.o

src/Engine/Font.i: src/Engine/Font.cpp.i

.PHONY : src/Engine/Font.i

# target to preprocess a source file
src/Engine/Font.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Font.cpp.i
.PHONY : src/Engine/Font.cpp.i

src/Engine/Font.s: src/Engine/Font.cpp.s

.PHONY : src/Engine/Font.s

# target to generate assembly for a file
src/Engine/Font.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Font.cpp.s
.PHONY : src/Engine/Font.cpp.s

src/Engine/GLEW/glew.o: src/Engine/GLEW/glew.c.o

.PHONY : src/Engine/GLEW/glew.o

# target to build an object file
src/Engine/GLEW/glew.c.o:
	$(MAKE) -f CMakeFiles/GLEW.dir/build.make CMakeFiles/GLEW.dir/src/Engine/GLEW/glew.c.o
.PHONY : src/Engine/GLEW/glew.c.o

src/Engine/GLEW/glew.i: src/Engine/GLEW/glew.c.i

.PHONY : src/Engine/GLEW/glew.i

# target to preprocess a source file
src/Engine/GLEW/glew.c.i:
	$(MAKE) -f CMakeFiles/GLEW.dir/build.make CMakeFiles/GLEW.dir/src/Engine/GLEW/glew.c.i
.PHONY : src/Engine/GLEW/glew.c.i

src/Engine/GLEW/glew.s: src/Engine/GLEW/glew.c.s

.PHONY : src/Engine/GLEW/glew.s

# target to generate assembly for a file
src/Engine/GLEW/glew.c.s:
	$(MAKE) -f CMakeFiles/GLEW.dir/build.make CMakeFiles/GLEW.dir/src/Engine/GLEW/glew.c.s
.PHONY : src/Engine/GLEW/glew.c.s

src/Engine/Graphics.o: src/Engine/Graphics.cpp.o

.PHONY : src/Engine/Graphics.o

# target to build an object file
src/Engine/Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Graphics.cpp.o
.PHONY : src/Engine/Graphics.cpp.o

src/Engine/Graphics.i: src/Engine/Graphics.cpp.i

.PHONY : src/Engine/Graphics.i

# target to preprocess a source file
src/Engine/Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Graphics.cpp.i
.PHONY : src/Engine/Graphics.cpp.i

src/Engine/Graphics.s: src/Engine/Graphics.cpp.s

.PHONY : src/Engine/Graphics.s

# target to generate assembly for a file
src/Engine/Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Graphics.cpp.s
.PHONY : src/Engine/Graphics.cpp.s

src/Engine/Input.o: src/Engine/Input.cpp.o

.PHONY : src/Engine/Input.o

# target to build an object file
src/Engine/Input.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Input.cpp.o
.PHONY : src/Engine/Input.cpp.o

src/Engine/Input.i: src/Engine/Input.cpp.i

.PHONY : src/Engine/Input.i

# target to preprocess a source file
src/Engine/Input.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Input.cpp.i
.PHONY : src/Engine/Input.cpp.i

src/Engine/Input.s: src/Engine/Input.cpp.s

.PHONY : src/Engine/Input.s

# target to generate assembly for a file
src/Engine/Input.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Input.cpp.s
.PHONY : src/Engine/Input.cpp.s

src/Engine/JSON/Jzon.o: src/Engine/JSON/Jzon.cpp.o

.PHONY : src/Engine/JSON/Jzon.o

# target to build an object file
src/Engine/JSON/Jzon.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/JSON/Jzon.cpp.o
.PHONY : src/Engine/JSON/Jzon.cpp.o

src/Engine/JSON/Jzon.i: src/Engine/JSON/Jzon.cpp.i

.PHONY : src/Engine/JSON/Jzon.i

# target to preprocess a source file
src/Engine/JSON/Jzon.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/JSON/Jzon.cpp.i
.PHONY : src/Engine/JSON/Jzon.cpp.i

src/Engine/JSON/Jzon.s: src/Engine/JSON/Jzon.cpp.s

.PHONY : src/Engine/JSON/Jzon.s

# target to generate assembly for a file
src/Engine/JSON/Jzon.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/JSON/Jzon.cpp.s
.PHONY : src/Engine/JSON/Jzon.cpp.s

src/Engine/Network.o: src/Engine/Network.cpp.o

.PHONY : src/Engine/Network.o

# target to build an object file
src/Engine/Network.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Network.cpp.o
.PHONY : src/Engine/Network.cpp.o

src/Engine/Network.i: src/Engine/Network.cpp.i

.PHONY : src/Engine/Network.i

# target to preprocess a source file
src/Engine/Network.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Network.cpp.i
.PHONY : src/Engine/Network.cpp.i

src/Engine/Network.s: src/Engine/Network.cpp.s

.PHONY : src/Engine/Network.s

# target to generate assembly for a file
src/Engine/Network.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Network.cpp.s
.PHONY : src/Engine/Network.cpp.s

src/Engine/Object.o: src/Engine/Object.cpp.o

.PHONY : src/Engine/Object.o

# target to build an object file
src/Engine/Object.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Object.cpp.o
.PHONY : src/Engine/Object.cpp.o

src/Engine/Object.i: src/Engine/Object.cpp.i

.PHONY : src/Engine/Object.i

# target to preprocess a source file
src/Engine/Object.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Object.cpp.i
.PHONY : src/Engine/Object.cpp.i

src/Engine/Object.s: src/Engine/Object.cpp.s

.PHONY : src/Engine/Object.s

# target to generate assembly for a file
src/Engine/Object.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Object.cpp.s
.PHONY : src/Engine/Object.cpp.s

src/Engine/Packets.o: src/Engine/Packets.cpp.o

.PHONY : src/Engine/Packets.o

# target to build an object file
src/Engine/Packets.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Packets.cpp.o
.PHONY : src/Engine/Packets.cpp.o

src/Engine/Packets.i: src/Engine/Packets.cpp.i

.PHONY : src/Engine/Packets.i

# target to preprocess a source file
src/Engine/Packets.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Packets.cpp.i
.PHONY : src/Engine/Packets.cpp.i

src/Engine/Packets.s: src/Engine/Packets.cpp.s

.PHONY : src/Engine/Packets.s

# target to generate assembly for a file
src/Engine/Packets.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Packets.cpp.s
.PHONY : src/Engine/Packets.cpp.s

src/Engine/SOIL/SOIL.o: src/Engine/SOIL/SOIL.c.o

.PHONY : src/Engine/SOIL/SOIL.o

# target to build an object file
src/Engine/SOIL/SOIL.c.o:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/SOIL.c.o
.PHONY : src/Engine/SOIL/SOIL.c.o

src/Engine/SOIL/SOIL.i: src/Engine/SOIL/SOIL.c.i

.PHONY : src/Engine/SOIL/SOIL.i

# target to preprocess a source file
src/Engine/SOIL/SOIL.c.i:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/SOIL.c.i
.PHONY : src/Engine/SOIL/SOIL.c.i

src/Engine/SOIL/SOIL.s: src/Engine/SOIL/SOIL.c.s

.PHONY : src/Engine/SOIL/SOIL.s

# target to generate assembly for a file
src/Engine/SOIL/SOIL.c.s:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/SOIL.c.s
.PHONY : src/Engine/SOIL/SOIL.c.s

src/Engine/SOIL/image_DXT.o: src/Engine/SOIL/image_DXT.c.o

.PHONY : src/Engine/SOIL/image_DXT.o

# target to build an object file
src/Engine/SOIL/image_DXT.c.o:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/image_DXT.c.o
.PHONY : src/Engine/SOIL/image_DXT.c.o

src/Engine/SOIL/image_DXT.i: src/Engine/SOIL/image_DXT.c.i

.PHONY : src/Engine/SOIL/image_DXT.i

# target to preprocess a source file
src/Engine/SOIL/image_DXT.c.i:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/image_DXT.c.i
.PHONY : src/Engine/SOIL/image_DXT.c.i

src/Engine/SOIL/image_DXT.s: src/Engine/SOIL/image_DXT.c.s

.PHONY : src/Engine/SOIL/image_DXT.s

# target to generate assembly for a file
src/Engine/SOIL/image_DXT.c.s:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/image_DXT.c.s
.PHONY : src/Engine/SOIL/image_DXT.c.s

src/Engine/SOIL/image_helper.o: src/Engine/SOIL/image_helper.c.o

.PHONY : src/Engine/SOIL/image_helper.o

# target to build an object file
src/Engine/SOIL/image_helper.c.o:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/image_helper.c.o
.PHONY : src/Engine/SOIL/image_helper.c.o

src/Engine/SOIL/image_helper.i: src/Engine/SOIL/image_helper.c.i

.PHONY : src/Engine/SOIL/image_helper.i

# target to preprocess a source file
src/Engine/SOIL/image_helper.c.i:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/image_helper.c.i
.PHONY : src/Engine/SOIL/image_helper.c.i

src/Engine/SOIL/image_helper.s: src/Engine/SOIL/image_helper.c.s

.PHONY : src/Engine/SOIL/image_helper.s

# target to generate assembly for a file
src/Engine/SOIL/image_helper.c.s:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/image_helper.c.s
.PHONY : src/Engine/SOIL/image_helper.c.s

src/Engine/SOIL/stb_image_aug.o: src/Engine/SOIL/stb_image_aug.c.o

.PHONY : src/Engine/SOIL/stb_image_aug.o

# target to build an object file
src/Engine/SOIL/stb_image_aug.c.o:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/stb_image_aug.c.o
.PHONY : src/Engine/SOIL/stb_image_aug.c.o

src/Engine/SOIL/stb_image_aug.i: src/Engine/SOIL/stb_image_aug.c.i

.PHONY : src/Engine/SOIL/stb_image_aug.i

# target to preprocess a source file
src/Engine/SOIL/stb_image_aug.c.i:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/stb_image_aug.c.i
.PHONY : src/Engine/SOIL/stb_image_aug.c.i

src/Engine/SOIL/stb_image_aug.s: src/Engine/SOIL/stb_image_aug.c.s

.PHONY : src/Engine/SOIL/stb_image_aug.s

# target to generate assembly for a file
src/Engine/SOIL/stb_image_aug.c.s:
	$(MAKE) -f CMakeFiles/SOIL.dir/build.make CMakeFiles/SOIL.dir/src/Engine/SOIL/stb_image_aug.c.s
.PHONY : src/Engine/SOIL/stb_image_aug.c.s

src/Engine/Shader.o: src/Engine/Shader.cpp.o

.PHONY : src/Engine/Shader.o

# target to build an object file
src/Engine/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Shader.cpp.o
.PHONY : src/Engine/Shader.cpp.o

src/Engine/Shader.i: src/Engine/Shader.cpp.i

.PHONY : src/Engine/Shader.i

# target to preprocess a source file
src/Engine/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Shader.cpp.i
.PHONY : src/Engine/Shader.cpp.i

src/Engine/Shader.s: src/Engine/Shader.cpp.s

.PHONY : src/Engine/Shader.s

# target to generate assembly for a file
src/Engine/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Shader.cpp.s
.PHONY : src/Engine/Shader.cpp.s

src/Engine/Shapes.o: src/Engine/Shapes.cpp.o

.PHONY : src/Engine/Shapes.o

# target to build an object file
src/Engine/Shapes.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Shapes.cpp.o
.PHONY : src/Engine/Shapes.cpp.o

src/Engine/Shapes.i: src/Engine/Shapes.cpp.i

.PHONY : src/Engine/Shapes.i

# target to preprocess a source file
src/Engine/Shapes.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Shapes.cpp.i
.PHONY : src/Engine/Shapes.cpp.i

src/Engine/Shapes.s: src/Engine/Shapes.cpp.s

.PHONY : src/Engine/Shapes.s

# target to generate assembly for a file
src/Engine/Shapes.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Shapes.cpp.s
.PHONY : src/Engine/Shapes.cpp.s

src/Engine/Texture.o: src/Engine/Texture.cpp.o

.PHONY : src/Engine/Texture.o

# target to build an object file
src/Engine/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Texture.cpp.o
.PHONY : src/Engine/Texture.cpp.o

src/Engine/Texture.i: src/Engine/Texture.cpp.i

.PHONY : src/Engine/Texture.i

# target to preprocess a source file
src/Engine/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Texture.cpp.i
.PHONY : src/Engine/Texture.cpp.i

src/Engine/Texture.s: src/Engine/Texture.cpp.s

.PHONY : src/Engine/Texture.s

# target to generate assembly for a file
src/Engine/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Texture.cpp.s
.PHONY : src/Engine/Texture.cpp.s

src/Engine/Tileset.o: src/Engine/Tileset.cpp.o

.PHONY : src/Engine/Tileset.o

# target to build an object file
src/Engine/Tileset.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tileset.cpp.o
.PHONY : src/Engine/Tileset.cpp.o

src/Engine/Tileset.i: src/Engine/Tileset.cpp.i

.PHONY : src/Engine/Tileset.i

# target to preprocess a source file
src/Engine/Tileset.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tileset.cpp.i
.PHONY : src/Engine/Tileset.cpp.i

src/Engine/Tileset.s: src/Engine/Tileset.cpp.s

.PHONY : src/Engine/Tileset.s

# target to generate assembly for a file
src/Engine/Tileset.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tileset.cpp.s
.PHONY : src/Engine/Tileset.cpp.s

src/Engine/Tools/Files.o: src/Engine/Tools/Files.cpp.o

.PHONY : src/Engine/Tools/Files.o

# target to build an object file
src/Engine/Tools/Files.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Files.cpp.o
.PHONY : src/Engine/Tools/Files.cpp.o

src/Engine/Tools/Files.i: src/Engine/Tools/Files.cpp.i

.PHONY : src/Engine/Tools/Files.i

# target to preprocess a source file
src/Engine/Tools/Files.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Files.cpp.i
.PHONY : src/Engine/Tools/Files.cpp.i

src/Engine/Tools/Files.s: src/Engine/Tools/Files.cpp.s

.PHONY : src/Engine/Tools/Files.s

# target to generate assembly for a file
src/Engine/Tools/Files.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Files.cpp.s
.PHONY : src/Engine/Tools/Files.cpp.s

src/Engine/Tools/Hash.o: src/Engine/Tools/Hash.cpp.o

.PHONY : src/Engine/Tools/Hash.o

# target to build an object file
src/Engine/Tools/Hash.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Hash.cpp.o
.PHONY : src/Engine/Tools/Hash.cpp.o

src/Engine/Tools/Hash.i: src/Engine/Tools/Hash.cpp.i

.PHONY : src/Engine/Tools/Hash.i

# target to preprocess a source file
src/Engine/Tools/Hash.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Hash.cpp.i
.PHONY : src/Engine/Tools/Hash.cpp.i

src/Engine/Tools/Hash.s: src/Engine/Tools/Hash.cpp.s

.PHONY : src/Engine/Tools/Hash.s

# target to generate assembly for a file
src/Engine/Tools/Hash.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Hash.cpp.s
.PHONY : src/Engine/Tools/Hash.cpp.s

src/Engine/Tools/Log.o: src/Engine/Tools/Log.cpp.o

.PHONY : src/Engine/Tools/Log.o

# target to build an object file
src/Engine/Tools/Log.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Log.cpp.o
.PHONY : src/Engine/Tools/Log.cpp.o

src/Engine/Tools/Log.i: src/Engine/Tools/Log.cpp.i

.PHONY : src/Engine/Tools/Log.i

# target to preprocess a source file
src/Engine/Tools/Log.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Log.cpp.i
.PHONY : src/Engine/Tools/Log.cpp.i

src/Engine/Tools/Log.s: src/Engine/Tools/Log.cpp.s

.PHONY : src/Engine/Tools/Log.s

# target to generate assembly for a file
src/Engine/Tools/Log.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Log.cpp.s
.PHONY : src/Engine/Tools/Log.cpp.s

src/Engine/Tools/MD5.o: src/Engine/Tools/MD5.cpp.o

.PHONY : src/Engine/Tools/MD5.o

# target to build an object file
src/Engine/Tools/MD5.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/MD5.cpp.o
.PHONY : src/Engine/Tools/MD5.cpp.o

src/Engine/Tools/MD5.i: src/Engine/Tools/MD5.cpp.i

.PHONY : src/Engine/Tools/MD5.i

# target to preprocess a source file
src/Engine/Tools/MD5.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/MD5.cpp.i
.PHONY : src/Engine/Tools/MD5.cpp.i

src/Engine/Tools/MD5.s: src/Engine/Tools/MD5.cpp.s

.PHONY : src/Engine/Tools/MD5.s

# target to generate assembly for a file
src/Engine/Tools/MD5.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/MD5.cpp.s
.PHONY : src/Engine/Tools/MD5.cpp.s

src/Engine/Tools/Math.o: src/Engine/Tools/Math.cpp.o

.PHONY : src/Engine/Tools/Math.o

# target to build an object file
src/Engine/Tools/Math.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Math.cpp.o
.PHONY : src/Engine/Tools/Math.cpp.o

src/Engine/Tools/Math.i: src/Engine/Tools/Math.cpp.i

.PHONY : src/Engine/Tools/Math.i

# target to preprocess a source file
src/Engine/Tools/Math.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Math.cpp.i
.PHONY : src/Engine/Tools/Math.cpp.i

src/Engine/Tools/Math.s: src/Engine/Tools/Math.cpp.s

.PHONY : src/Engine/Tools/Math.s

# target to generate assembly for a file
src/Engine/Tools/Math.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Math.cpp.s
.PHONY : src/Engine/Tools/Math.cpp.s

src/Engine/Tools/String.o: src/Engine/Tools/String.cpp.o

.PHONY : src/Engine/Tools/String.o

# target to build an object file
src/Engine/Tools/String.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/String.cpp.o
.PHONY : src/Engine/Tools/String.cpp.o

src/Engine/Tools/String.i: src/Engine/Tools/String.cpp.i

.PHONY : src/Engine/Tools/String.i

# target to preprocess a source file
src/Engine/Tools/String.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/String.cpp.i
.PHONY : src/Engine/Tools/String.cpp.i

src/Engine/Tools/String.s: src/Engine/Tools/String.cpp.s

.PHONY : src/Engine/Tools/String.s

# target to generate assembly for a file
src/Engine/Tools/String.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/String.cpp.s
.PHONY : src/Engine/Tools/String.cpp.s

src/Engine/Tools/System.o: src/Engine/Tools/System.cpp.o

.PHONY : src/Engine/Tools/System.o

# target to build an object file
src/Engine/Tools/System.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/System.cpp.o
.PHONY : src/Engine/Tools/System.cpp.o

src/Engine/Tools/System.i: src/Engine/Tools/System.cpp.i

.PHONY : src/Engine/Tools/System.i

# target to preprocess a source file
src/Engine/Tools/System.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/System.cpp.i
.PHONY : src/Engine/Tools/System.cpp.i

src/Engine/Tools/System.s: src/Engine/Tools/System.cpp.s

.PHONY : src/Engine/Tools/System.s

# target to generate assembly for a file
src/Engine/Tools/System.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/System.cpp.s
.PHONY : src/Engine/Tools/System.cpp.s

src/Engine/Tools/Time.o: src/Engine/Tools/Time.cpp.o

.PHONY : src/Engine/Tools/Time.o

# target to build an object file
src/Engine/Tools/Time.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Time.cpp.o
.PHONY : src/Engine/Tools/Time.cpp.o

src/Engine/Tools/Time.i: src/Engine/Tools/Time.cpp.i

.PHONY : src/Engine/Tools/Time.i

# target to preprocess a source file
src/Engine/Tools/Time.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Time.cpp.i
.PHONY : src/Engine/Tools/Time.cpp.i

src/Engine/Tools/Time.s: src/Engine/Tools/Time.cpp.s

.PHONY : src/Engine/Tools/Time.s

# target to generate assembly for a file
src/Engine/Tools/Time.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Tools/Time.cpp.s
.PHONY : src/Engine/Tools/Time.cpp.s

src/Engine/Types.o: src/Engine/Types.cpp.o

.PHONY : src/Engine/Types.o

# target to build an object file
src/Engine/Types.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Types.cpp.o
.PHONY : src/Engine/Types.cpp.o

src/Engine/Types.i: src/Engine/Types.cpp.i

.PHONY : src/Engine/Types.i

# target to preprocess a source file
src/Engine/Types.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Types.cpp.i
.PHONY : src/Engine/Types.cpp.i

src/Engine/Types.s: src/Engine/Types.cpp.s

.PHONY : src/Engine/Types.s

# target to generate assembly for a file
src/Engine/Types.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/Types.cpp.s
.PHONY : src/Engine/Types.cpp.s

src/Engine/View.o: src/Engine/View.cpp.o

.PHONY : src/Engine/View.o

# target to build an object file
src/Engine/View.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/View.cpp.o
.PHONY : src/Engine/View.cpp.o

src/Engine/View.i: src/Engine/View.cpp.i

.PHONY : src/Engine/View.i

# target to preprocess a source file
src/Engine/View.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/View.cpp.i
.PHONY : src/Engine/View.cpp.i

src/Engine/View.s: src/Engine/View.cpp.s

.PHONY : src/Engine/View.s

# target to generate assembly for a file
src/Engine/View.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/View.cpp.s
.PHONY : src/Engine/View.cpp.s

src/Engine/World.o: src/Engine/World.cpp.o

.PHONY : src/Engine/World.o

# target to build an object file
src/Engine/World.cpp.o:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/World.cpp.o
.PHONY : src/Engine/World.cpp.o

src/Engine/World.i: src/Engine/World.cpp.i

.PHONY : src/Engine/World.i

# target to preprocess a source file
src/Engine/World.cpp.i:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/World.cpp.i
.PHONY : src/Engine/World.cpp.i

src/Engine/World.s: src/Engine/World.cpp.s

.PHONY : src/Engine/World.s

# target to generate assembly for a file
src/Engine/World.cpp.s:
	$(MAKE) -f CMakeFiles/nite.dir/build.make CMakeFiles/nite.dir/src/Engine/World.cpp.s
.PHONY : src/Engine/World.cpp.s

src/Entity.o: src/Entity.cpp.o

.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i

.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s

.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Inventory.o: src/Inventory.cpp.o

.PHONY : src/Inventory.o

# target to build an object file
src/Inventory.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Inventory.cpp.o
.PHONY : src/Inventory.cpp.o

src/Inventory.i: src/Inventory.cpp.i

.PHONY : src/Inventory.i

# target to preprocess a source file
src/Inventory.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Inventory.cpp.i
.PHONY : src/Inventory.cpp.i

src/Inventory.s: src/Inventory.cpp.s

.PHONY : src/Inventory.s

# target to generate assembly for a file
src/Inventory.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Inventory.cpp.s
.PHONY : src/Inventory.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/Mob.o: src/Mob.cpp.o

.PHONY : src/Mob.o

# target to build an object file
src/Mob.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Mob.cpp.o
.PHONY : src/Mob.cpp.o

src/Mob.i: src/Mob.cpp.i

.PHONY : src/Mob.i

# target to preprocess a source file
src/Mob.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Mob.cpp.i
.PHONY : src/Mob.cpp.i

src/Mob.s: src/Mob.cpp.s

.PHONY : src/Mob.s

# target to generate assembly for a file
src/Mob.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Mob.cpp.s
.PHONY : src/Mob.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Sword.o: src/Sword.cpp.o

.PHONY : src/Sword.o

# target to build an object file
src/Sword.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Sword.cpp.o
.PHONY : src/Sword.cpp.o

src/Sword.i: src/Sword.cpp.i

.PHONY : src/Sword.i

# target to preprocess a source file
src/Sword.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Sword.cpp.i
.PHONY : src/Sword.cpp.i

src/Sword.s: src/Sword.cpp.s

.PHONY : src/Sword.s

# target to generate assembly for a file
src/Sword.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/Sword.cpp.s
.PHONY : src/Sword.cpp.s

src/UI/BaseUIComponent.o: src/UI/BaseUIComponent.cpp.o

.PHONY : src/UI/BaseUIComponent.o

# target to build an object file
src/UI/BaseUIComponent.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/BaseUIComponent.cpp.o
.PHONY : src/UI/BaseUIComponent.cpp.o

src/UI/BaseUIComponent.i: src/UI/BaseUIComponent.cpp.i

.PHONY : src/UI/BaseUIComponent.i

# target to preprocess a source file
src/UI/BaseUIComponent.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/BaseUIComponent.cpp.i
.PHONY : src/UI/BaseUIComponent.cpp.i

src/UI/BaseUIComponent.s: src/UI/BaseUIComponent.cpp.s

.PHONY : src/UI/BaseUIComponent.s

# target to generate assembly for a file
src/UI/BaseUIComponent.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/BaseUIComponent.cpp.s
.PHONY : src/UI/BaseUIComponent.cpp.s

src/UI/ButtonUI.o: src/UI/ButtonUI.cpp.o

.PHONY : src/UI/ButtonUI.o

# target to build an object file
src/UI/ButtonUI.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/ButtonUI.cpp.o
.PHONY : src/UI/ButtonUI.cpp.o

src/UI/ButtonUI.i: src/UI/ButtonUI.cpp.i

.PHONY : src/UI/ButtonUI.i

# target to preprocess a source file
src/UI/ButtonUI.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/ButtonUI.cpp.i
.PHONY : src/UI/ButtonUI.cpp.i

src/UI/ButtonUI.s: src/UI/ButtonUI.cpp.s

.PHONY : src/UI/ButtonUI.s

# target to generate assembly for a file
src/UI/ButtonUI.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/ButtonUI.cpp.s
.PHONY : src/UI/ButtonUI.cpp.s

src/UI/CheckboxUI.o: src/UI/CheckboxUI.cpp.o

.PHONY : src/UI/CheckboxUI.o

# target to build an object file
src/UI/CheckboxUI.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/CheckboxUI.cpp.o
.PHONY : src/UI/CheckboxUI.cpp.o

src/UI/CheckboxUI.i: src/UI/CheckboxUI.cpp.i

.PHONY : src/UI/CheckboxUI.i

# target to preprocess a source file
src/UI/CheckboxUI.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/CheckboxUI.cpp.i
.PHONY : src/UI/CheckboxUI.cpp.i

src/UI/CheckboxUI.s: src/UI/CheckboxUI.cpp.s

.PHONY : src/UI/CheckboxUI.s

# target to generate assembly for a file
src/UI/CheckboxUI.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/CheckboxUI.cpp.s
.PHONY : src/UI/CheckboxUI.cpp.s

src/UI/PanelUI.o: src/UI/PanelUI.cpp.o

.PHONY : src/UI/PanelUI.o

# target to build an object file
src/UI/PanelUI.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/PanelUI.cpp.o
.PHONY : src/UI/PanelUI.cpp.o

src/UI/PanelUI.i: src/UI/PanelUI.cpp.i

.PHONY : src/UI/PanelUI.i

# target to preprocess a source file
src/UI/PanelUI.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/PanelUI.cpp.i
.PHONY : src/UI/PanelUI.cpp.i

src/UI/PanelUI.s: src/UI/PanelUI.cpp.s

.PHONY : src/UI/PanelUI.s

# target to generate assembly for a file
src/UI/PanelUI.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/PanelUI.cpp.s
.PHONY : src/UI/PanelUI.cpp.s

src/UI/TextUI.o: src/UI/TextUI.cpp.o

.PHONY : src/UI/TextUI.o

# target to build an object file
src/UI/TextUI.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/TextUI.cpp.o
.PHONY : src/UI/TextUI.cpp.o

src/UI/TextUI.i: src/UI/TextUI.cpp.i

.PHONY : src/UI/TextUI.i

# target to preprocess a source file
src/UI/TextUI.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/TextUI.cpp.i
.PHONY : src/UI/TextUI.cpp.i

src/UI/TextUI.s: src/UI/TextUI.cpp.s

.PHONY : src/UI/TextUI.s

# target to generate assembly for a file
src/UI/TextUI.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/TextUI.cpp.s
.PHONY : src/UI/TextUI.cpp.s

src/UI/UI.o: src/UI/UI.cpp.o

.PHONY : src/UI/UI.o

# target to build an object file
src/UI/UI.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/UI.cpp.o
.PHONY : src/UI/UI.cpp.o

src/UI/UI.i: src/UI/UI.cpp.i

.PHONY : src/UI/UI.i

# target to preprocess a source file
src/UI/UI.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/UI.cpp.i
.PHONY : src/UI/UI.cpp.i

src/UI/UI.s: src/UI/UI.cpp.s

.PHONY : src/UI/UI.s

# target to generate assembly for a file
src/UI/UI.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/UI.cpp.s
.PHONY : src/UI/UI.cpp.s

src/UI/WindowUI.o: src/UI/WindowUI.cpp.o

.PHONY : src/UI/WindowUI.o

# target to build an object file
src/UI/WindowUI.cpp.o:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/WindowUI.cpp.o
.PHONY : src/UI/WindowUI.cpp.o

src/UI/WindowUI.i: src/UI/WindowUI.cpp.i

.PHONY : src/UI/WindowUI.i

# target to preprocess a source file
src/UI/WindowUI.cpp.i:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/WindowUI.cpp.i
.PHONY : src/UI/WindowUI.cpp.i

src/UI/WindowUI.s: src/UI/WindowUI.cpp.s

.PHONY : src/UI/WindowUI.s

# target to generate assembly for a file
src/UI/WindowUI.cpp.s:
	$(MAKE) -f CMakeFiles/src.dir/build.make CMakeFiles/src.dir/src/UI/WindowUI.cpp.s
.PHONY : src/UI/WindowUI.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Game"
	@echo "... rebuild_cache"
	@echo "... SOIL"
	@echo "... GLEW"
	@echo "... nite"
	@echo "... src"
	@echo "... src/AI/AI.o"
	@echo "... src/AI/AI.i"
	@echo "... src/AI/AI.s"
	@echo "... src/Engine/Animation.o"
	@echo "... src/Engine/Animation.i"
	@echo "... src/Engine/Animation.s"
	@echo "... src/Engine/Audio.o"
	@echo "... src/Engine/Audio.i"
	@echo "... src/Engine/Audio.s"
	@echo "... src/Engine/Console.o"
	@echo "... src/Engine/Console.i"
	@echo "... src/Engine/Console.s"
	@echo "... src/Engine/Font.o"
	@echo "... src/Engine/Font.i"
	@echo "... src/Engine/Font.s"
	@echo "... src/Engine/GLEW/glew.o"
	@echo "... src/Engine/GLEW/glew.i"
	@echo "... src/Engine/GLEW/glew.s"
	@echo "... src/Engine/Graphics.o"
	@echo "... src/Engine/Graphics.i"
	@echo "... src/Engine/Graphics.s"
	@echo "... src/Engine/Input.o"
	@echo "... src/Engine/Input.i"
	@echo "... src/Engine/Input.s"
	@echo "... src/Engine/JSON/Jzon.o"
	@echo "... src/Engine/JSON/Jzon.i"
	@echo "... src/Engine/JSON/Jzon.s"
	@echo "... src/Engine/Network.o"
	@echo "... src/Engine/Network.i"
	@echo "... src/Engine/Network.s"
	@echo "... src/Engine/Object.o"
	@echo "... src/Engine/Object.i"
	@echo "... src/Engine/Object.s"
	@echo "... src/Engine/Packets.o"
	@echo "... src/Engine/Packets.i"
	@echo "... src/Engine/Packets.s"
	@echo "... src/Engine/SOIL/SOIL.o"
	@echo "... src/Engine/SOIL/SOIL.i"
	@echo "... src/Engine/SOIL/SOIL.s"
	@echo "... src/Engine/SOIL/image_DXT.o"
	@echo "... src/Engine/SOIL/image_DXT.i"
	@echo "... src/Engine/SOIL/image_DXT.s"
	@echo "... src/Engine/SOIL/image_helper.o"
	@echo "... src/Engine/SOIL/image_helper.i"
	@echo "... src/Engine/SOIL/image_helper.s"
	@echo "... src/Engine/SOIL/stb_image_aug.o"
	@echo "... src/Engine/SOIL/stb_image_aug.i"
	@echo "... src/Engine/SOIL/stb_image_aug.s"
	@echo "... src/Engine/Shader.o"
	@echo "... src/Engine/Shader.i"
	@echo "... src/Engine/Shader.s"
	@echo "... src/Engine/Shapes.o"
	@echo "... src/Engine/Shapes.i"
	@echo "... src/Engine/Shapes.s"
	@echo "... src/Engine/Texture.o"
	@echo "... src/Engine/Texture.i"
	@echo "... src/Engine/Texture.s"
	@echo "... src/Engine/Tileset.o"
	@echo "... src/Engine/Tileset.i"
	@echo "... src/Engine/Tileset.s"
	@echo "... src/Engine/Tools/Files.o"
	@echo "... src/Engine/Tools/Files.i"
	@echo "... src/Engine/Tools/Files.s"
	@echo "... src/Engine/Tools/Hash.o"
	@echo "... src/Engine/Tools/Hash.i"
	@echo "... src/Engine/Tools/Hash.s"
	@echo "... src/Engine/Tools/Log.o"
	@echo "... src/Engine/Tools/Log.i"
	@echo "... src/Engine/Tools/Log.s"
	@echo "... src/Engine/Tools/MD5.o"
	@echo "... src/Engine/Tools/MD5.i"
	@echo "... src/Engine/Tools/MD5.s"
	@echo "... src/Engine/Tools/Math.o"
	@echo "... src/Engine/Tools/Math.i"
	@echo "... src/Engine/Tools/Math.s"
	@echo "... src/Engine/Tools/String.o"
	@echo "... src/Engine/Tools/String.i"
	@echo "... src/Engine/Tools/String.s"
	@echo "... src/Engine/Tools/System.o"
	@echo "... src/Engine/Tools/System.i"
	@echo "... src/Engine/Tools/System.s"
	@echo "... src/Engine/Tools/Time.o"
	@echo "... src/Engine/Tools/Time.i"
	@echo "... src/Engine/Tools/Time.s"
	@echo "... src/Engine/Types.o"
	@echo "... src/Engine/Types.i"
	@echo "... src/Engine/Types.s"
	@echo "... src/Engine/View.o"
	@echo "... src/Engine/View.i"
	@echo "... src/Engine/View.s"
	@echo "... src/Engine/World.o"
	@echo "... src/Engine/World.i"
	@echo "... src/Engine/World.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Inventory.o"
	@echo "... src/Inventory.i"
	@echo "... src/Inventory.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Mob.o"
	@echo "... src/Mob.i"
	@echo "... src/Mob.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Sword.o"
	@echo "... src/Sword.i"
	@echo "... src/Sword.s"
	@echo "... src/UI/BaseUIComponent.o"
	@echo "... src/UI/BaseUIComponent.i"
	@echo "... src/UI/BaseUIComponent.s"
	@echo "... src/UI/ButtonUI.o"
	@echo "... src/UI/ButtonUI.i"
	@echo "... src/UI/ButtonUI.s"
	@echo "... src/UI/CheckboxUI.o"
	@echo "... src/UI/CheckboxUI.i"
	@echo "... src/UI/CheckboxUI.s"
	@echo "... src/UI/PanelUI.o"
	@echo "... src/UI/PanelUI.i"
	@echo "... src/UI/PanelUI.s"
	@echo "... src/UI/TextUI.o"
	@echo "... src/UI/TextUI.i"
	@echo "... src/UI/TextUI.s"
	@echo "... src/UI/UI.o"
	@echo "... src/UI/UI.i"
	@echo "... src/UI/UI.s"
	@echo "... src/UI/WindowUI.o"
	@echo "... src/UI/WindowUI.i"
	@echo "... src/UI/WindowUI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

